name: Fast_Builder

on: 
  workflow_dispatch:
    inputs:
      DEVICE_NAME:
        description: 'Ready'
        required: true
        default: 'Ok'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Prepare the environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libfl-dev guile-2.2-dev
        sudo apt-get install -y curl git ftp lftp wget libarchive-tools ccache
        sudo apt-get install -y zip unzip tar gzip bzip2 rar unrar
        
    - name: Start Building Kernel
      run: |
        export KBUILD_BUILD_USER="${{ github.actor }}"
        export KBUILD_BUILD_HOST="${{ github.event.inputs.DEVICE_NAME }}"
        ./build

    - name: Set Properties
      id: props
      run: |
        echo "date=$(TZ=Asia/Jakarta date +%Y%m%d-%I%M%p)" >> $GITHUB_OUTPUT

    - name: Compressed as Archive
      run: |
        cd /home/runner/work/myKernel
        mkdir -p tempe
        cd out/arch/arm
        ls && cd /home/runner/work/myKernel
        cd out/arch/arm/boot
        ls && cd /home/runner/work/myKernel
        cp -r out/arch/arm/boot tempe
        cd tempe
        zip -r9 -y "${{ github.event.inputs.DEVICE_NAME }}-${{ steps.props.outputs.date }}.zip" .
        mv *.zip /home/runner/work/myKernel
        cd /home/runner/work/myKernel
        rm -rf tempe
        rm -rf out

    - name: Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: |
          /home/runner/work/myKernel/*.zip
          /home/runner/work/myKernel/build.log
        name: Compiled Kernel for ${{ github.event.inputs.DEVICE_NAME }} - ${{ steps.props.outputs.date }}
        draft: false
        prerelease: false
        tag: ${{ github.run_id }}-${{ steps.props.outputs.date }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ## Notes
            - Extract ${{ github.event.inputs.DEVICE_NAME }}-${{ steps.props.outputs.date }}.zip, look your newly-compiled kernel inside.
            - Include building logs.

    - name: Link of Release
      run: |
        echo "Enjoy your Newly Built Kernel"
        echo "https://github.com/${GITHUB_REPOSITORY}/releases/tag/${{ github.run_id }}-${{ steps.props.outputs.date }}"
