name: Cleaning done!

on:
  workflow_dispatch:

jobs:
  start-working:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Permission
      run: |
        cd ${GITHUB_WORKSPACE}
        chmod +x -R scripts
        
    - name: Delete
      uses: ./     
