name: Go

on: workflow_dispatch

jobs:
  run-script-file-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Make script executable (if needed)
        run: chmod +x build
      - name: Run the bash script file
        run: ./build
