name: Howl

on: 
  workflow_dispatch:
    inputs:
      DEVICE_NAME:
        description: 'Ready'
        required: true
        default: 'Ok'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Prepare the environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc gcc-aarch64-linux-gnu clang gcc-arm-linux-gnueabi libssl-dev libfl-dev guile-2.2-dev
        sudo apt-get install -y curl git ftp lftp wget libarchive-tools ccache
        sudo apt-get install -y zip unzip tar gzip bzip2 rar unrar which
        
    - name: Checkpoint
      run: |
        clang -v
        echo ----------------
        gcc -v
        echo ----------------
