name: Sedot

on: workflow_dispatch

jobs:
  run-script-file-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Permisi pak
        run: chmod +x unduh.sh
      - name: Tarik mang
        run: ./unduh.sh
